Repository ASFHyP3/sentinel1-orbits, pull requests merged in 2024-07, with the labels that each got.

#32 Modifications for ASF Standards
  .github/CODEOWNERS
  .github/workflows/changelog.yml
  .github/workflows/release.yml
  .github/workflows/tag-version.yml
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
Labels: bumpless

#33 Release v0.0.1
  .github/CODEOWNERS
  .github/workflows/changelog.yml
  .github/workflows/release.yml
  .github/workflows/tag-version.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  requirements-api.txt
  requirements-fetcher.txt
Labels: patch

#37 Refactor and gitignore
  .gitignore
  CHANGELOG.md
  apps/api/cloudformation.yml
  apps/fetcher/src/fetcher.py
Labels: patch

#38 Release 0.0.2
  .gitignore
  CHANGELOG.md
  apps/api/cloudformation.yml
  apps/fetcher/src/fetcher.py
Labels: patch

#40 Re-add TOOLS_BOT_PAK to release and tag actions
  .github/workflows/release.yml
  .github/workflows/tag-version.yml
Labels: bumpless

#43 Support for a Custom API Domain
  .github/workflows/deploy.yml
  CHANGELOG.md
  apps/api/cloudformation.yml
  cloudformation.yml
Labels: patch

#44 Release 0.0.3
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  .github/workflows/tag-version.yml
  CHANGELOG.md
  apps/api/cloudformation.yml
  cloudformation.yml
Labels: patch

#45 Add DomainName and CertificateArn params to deployment
  .github/workflows/deploy.yml
Labels: bumpless

#46 Bumpless Release
  .github/workflows/deploy.yml
Labels: bumpless

#49 Release v0.0.4
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  .github/workflows/deploy.yml
  CHANGELOG.md
  README.md
  apps/bucket/cloudformation.yml
  cloudformation.yml
Labels: patch

#50 use single quotes in deploy action to avoid special characters being …
  .github/actions/deploy/action.yml
Labels: bumpless

#55 Release v0.0.5
  .github/actions/deploy/action.yml
  CHANGELOG.md
  apps/bucket/cloudformation.yml
Labels: patch

#56 Separation of Bucket and Application Stacks
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  CHANGELOG.md
  apps/api/cloudformation.yml
  apps/bucket/cloudformation.yml
  apps/fetcher/cloudformation.yml
  cloudformation.yml
Labels: minor

#58 update template bucket name
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
Labels: bumpless

#59 Fix Bucket Policy Syntax Error
  apps/bucket/cloudformation.yml
Labels: bug, bumpless

#60 Give root Access to S3 Bucket Rather Than Named Role
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  apps/bucket/cloudformation.yml
  apps/fetcher/cloudformation.yml
Labels: bumpless

#57 add cloudformation template for creating deployment resources in open…
  cicd/opendata-cicd.yml
Labels: bumpless

#61 Release v0.1.0
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  CHANGELOG.md
  apps/api/cloudformation.yml
  apps/bucket/cloudformation.yml
  apps/fetcher/cloudformation.yml
  cicd/opendata-cicd.yml
  cloudformation.yml
Labels: minor

#63 Release v0.1.1
  CHANGELOG.md
  apps/bucket/cloudformation.yml
Labels: patch
